server:
  port: 8080

spring:
  application:
    name: PersonalFinance

  datasource:
    url: jdbc:postgresql://localhost:5432/financedb
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      format-sql: true
    show-sql: true

  security:
    user:
      name: user
      password: secret247

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

#logging:
#  level:
#    com.niyiment.finance: DEBUG
#    org.springframework.security: DEBUG
